### ISSUE TITLE
Deprecate "ELBO" arg to SVI; require object instead

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#1014]
(pulled out of #827)

@eb8680 suggested removing the string arg `loss` `SVI.__init__` and instead requiring an `ELBO` object: 
```diff
- svi = SVI(model, guide, optim, 'ELBO', ...)
+ elbo = Trace_ELBO(...)
+ SVI(model, guide, optim, elbo)
```

This is advantageous in that it makes it easier for users to implement custom losses, as e.g. requested in #958. This is a huge breaking change that will touch lots of files. It would be nice to finish this before 0.2 release.

## Tasks (in multiple small PRs)

- [x] #1018 add support for `loss` `ELBO` object to `SVI.__init__()`
- [x] #1018 remove support for `loss` function arg from `SVI.__init__()`
- [x] #1020 update all tests
- [x] #1021 update all examples
- [x] #1022 update all tutorials
- [ ] #1054 remove support for `loss` string arg from `SVI.__init__()`
- [ ] #1054 remove `ELBO.make()` factory

**Comment by fritzo** [comment]
@eb8680 I've assigned this to you since you volunteered at one point; if you're busy I could try to get to it next week.

**Comment by eb8680** [comment]
Happy to do this but it's going to cause so many merge conflicts that I'd rather wait until the end of next week

**Comment by martinjankowiak** [comment]
we should also consider whether we want to make other changes. for example `step()` could take a `accumulate_only` kwarg (grads aren't zeroed, no step is taken), etc etc. basically things that make it easier to monkey around with the objective function and the way gradients are taken

**Comment by fritzo** [comment]
> we should also consider whether we want to make other changes

I agree, and let's prioritize *breaking* changes to interface. I'm holding off on non-breaking changes that we can push until after launch, including: exposing a differentiable loss, adding an `accumulate_only` kwarg, etc. Let me know if you see any need for breaking changes.

**Comment by fehiepsi** [comment]
> including: exposing a differentiable loss
I like this for a long time and like the idea of @fritzo at https://github.com/uber/pyro/issues/583#issuecomment-348339390. We can implement `_loss_particle()` and `_loss_and_grads_particle` will calls `backward` on the output of `_loss_particle()`. Inherited custom loss can have benefits from that,
