### ISSUE TITLE
GP related checklist

### ISSUE THREAD

**Issue by fehiepsi** [uber/pyro#1041]
From some discussions in #1039, I would like to make the following (possible) changes before Pyro 0.2 if there is no objection:
- [ ] Rename SparseVariationalGP to VariationalSparseGP
- [ ] Rename SparseMultivariateNormal to LowRankMultivariateNormal
- [ ] Rename GPRegression, SparseGPRegression (cc @martinjankowiak )
- [ ] Rename `approx` argument of SparseGPRegression to `method`.
- [ ] Rename the flag `noiseless` in regression models to (might be) `with_noise`
- [ ] Update triangular solver because we have gpu `torch.trtrs` now in pytorch master (might remove the confusing `pack` and `unpack` method for triangular solver as previously used in gp module and use trtrs directly).
- [ ] Enable validation check and rerun bo tutorial.
- [ ] Add timer for sv-dkl example to record running time (to observe performance changes after some commits from pyro and pytorch).

**Comment by martinjankowiak** [comment]
i don't have strong feelings about most of these but you can probably leave `SparseVariationalGP` as is. 
`SparseMultivariateNormal` seems like the one that needs changing most

**Comment by fritzo** [comment]
@fehiepsi We're aiming to release mid-week next week.
- :+1: on any renaming you'd like to do
- if you have time to implement `torch.trtrs` by Monday then fine, otherwise it's fine to delay till 0.4.1
- :+1: on ebling validation in bo tutorial
- no need to add a timer before release, i think it's more important to focus on interface
