### ISSUE TITLE
Support PyTorch JIT compilation

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#1063]
What would it take to support JIT-compilation of an entire `SVI.step()`?

For motivation, consider [a beta bernoulli model](https://forum.pyro.ai/t/comparison-of-beta-bernoulli-process-in-edward-and-pyro/175) which is 10x slower in Pyro than Edward.

## Feasibility

PyTorch `@jit.compile` appears to be functional input->output. Therefore we would need to at least
1. run a warm-up iteration to populate the param store
2. expose the Pyro param store to the jit compiler
3. expose a helper `.differentiable_loss()` inside `loss_and_grads` (everything up to `.backward()`)

## Tasks

- [x] assess feasibility
- [x] #1109 refactor ELBO to expose `.differentiable_loss()` (see also #628)
- [x] #1126  add an abstract jit decorator to make it easy to write new jitted functions
- [x] #1276 Change to using `torch.jit.trace` instead of the deprecated `torch.jit.compile`
- [x] https://github.com/pytorch/pytorch/issues/10041 Support `broadcast_all()` in the jit
- [x] https://github.com/pytorch/pytorch/pull/10321 Support `Categorical.log_prob()` in the jit
- [x] #1296 add `--jit` option to SVI examples
- [x] #1299 support jit in HMC
- ~~add tutorial~~

## Remaining PyTorch issues

To see remaining PyTorch jit issues:
1. Install PyTorch master
    ```sh
    cd ~/github/pytorch/pytorch  # or wherever your clone lives
    git checkout master
    git pull
    python setup.py build develop
    ```
2. Run Pyro's jit tests with the `pytorch-0.4.1` branch of Pyro
    ```sh
    cd ~/github/uber/pyro  # or wherever your clone lives
    git checkout pytorch-0.4.1
    git pull
    make install
    make test-jit  # saves results to jit.log
    ```
Here is an example [jit.log](http://fritzo.org/temp/jit.log).

**Comment by eb8680** [comment]
Are any `torch.distributions` samplers or log-probabilities supported by the JIT at all?  Does the JIT have the same broadcasting semantics?

**Comment by fritzo** [comment]
I believe this is closed by #1431
