### ISSUE TITLE
Master issue for pyro.contrib.tracking

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#1185]
## Components

Data association in pyro.contrib.tracking.assignment (@fritzo):
- [x] #1186 multi-frame enumeration solver
- [x] #1190 flat assignment solvers (for data with one observation per frame)
- [x] #1194 dense multi-frame bp solver
- [x] #1217 tests of algebraic properties
- ~~sparse multi-frame bp solver~~

Motion models and measurement models:
- [x] ND gaussian/kalman filters (@jpchen)

Track maintenance utilities:
- [x] #1211 `ApproxSet` for cheap track initialization via space carving
- [x] #1211 Euclidean `LSH` for cheap track merging
- [x] #1219 A generic `merge_points()` function using `heapq` and `LSH`

Lots of examples
- [x] #1186 simple 1D example
- [x] #1394 tutorial on differentiable EKF
- ~~example of neural detector~~

## Design Questions:

- Will the generative model work at all, or will we need a factor-graph model?
- How should we encode exact inference via dynamic programming? E.g. unscented filtering via TraceEnum message passing, or Laplace approximation message passing (a la EKF).

**Comment by alicanb** [comment]
Re. metric evaluation, I've been going through some implementations online. It looks like pymot hasn't been maintained for a while... The evaluation suite that's used in [MOT Challenge](https://bitbucket.org/amilan/motchallenge-devkit) in Matlab, but there's a python version of it [here](https://github.com/cheind/py-motmetrics/tree/develop) but people have been complaining results are different from the original.
