### ISSUE TITLE
Work around torch.cuda.Tensor maximum dim limit

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#1380]
Much of Pyro's enumeration code requires sparse tensor dimensions, i.e. only a few dimensions of size > 1 but those dimensions are sparsely distributed, e.g. `shape=(3,1,1,1,1,1,14,1,1,1,1,1,1,1,1)`. However torch CUDA tensors have a maximum dim limit (25?). This is preventing message-passing algorithms from running in CUDA on large factor graphs #1379 .

## Proposed solution

One approach would be to create named dimensions rather than globally-positioned dimensions. We're already doing something similar with recycled `iarange`s, and we're already using named dimensions under-the-hood when using `einsum`.

## Tasks

- [x] #1405 Implement packed version of `contract_to_tensor`, e.g. `ubersum`
- [ ] track enumeration dims used by each tensor (like `cond_indep_stack` but not a stack)
- [ ] track dependencies to determine when an enum dim can be recycled. This is a difficult task and @eb8680 and @fritzo may implement multiple mechanisms, e.g.
    - static analysis for dependency tracking
    - context manager
    - python `del` statement
    - declare number of downstream dependencies of each node ("ref counting")
- [ ] switch from `UnpackedLogRing` to `PackedLogRing` in `contract_to_tensor`, when used in `traceenum_elbo.py`
- [ ] implement dim recycling

**Comment by fritzo** [comment]
This is now higher priority since @colesbury has notified us that PyTorch plans to limit tensors to 64 dimensions.
