### ISSUE TITLE
Write tech report on enumeration

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#1391]
See also #1355 

## Coding tasks

- [x] #1405 Create a general `ubersum` interface
- [x] #1408 Relax diamond constraint as much as possible
- [x] #1417 Create simple reference implementation with clear semantics
- [x] #1417 Add `ubersum` tests for computing marginals

**Comment by fritzo** [comment]
@martinjankowiak would  you be able to start a draft with rough paper structure? I think you can already write a substantial related work section.

**Comment by fritzo** [comment]
forthcoming
