### ISSUE TITLE
Test failures using PyTorch master

### ISSUE THREAD

**Issue by neerajprad** [uber/pyro#1418]
While most test failures on `pytorch-0.5.0` are resolved, the following tests are still failing with the latest master branch. Some of these are recent failures. 

CPU Tests:
 - [x] #1417 tests/ops/test_contract.py::test_ubersum_sizes (#1414)
 - [x] #1590 test_svi_irregular_batch_size[JitTraceEnum_ELBO]
 - [x] many HMC/NUTS tests with step size adaptation (#1487) wontfix - this is an upstream pytorch issue.
 - [ ] tests/contrib/oed/test_ewma.py::test_ewma - Assertion failures (#1373)
 - [ ] test_eig_lm[model5-design5-y-w-donsker_varadhan_eig-args5-True-0.3] (#1373)
 - [ ] test_eig_lm[model10-design10-y-w1-donsker_varadhan_eig-args10-True-0.3] (#1373)
 - [x] tests/infer/test_enum.py::test_mixture_of_diag_normals (Assertion failures) (#1425)

**Comment by fehiepsi** [comment]
Closed because these tests have been solved in #1617.
