### ISSUE TITLE
Create mini-version of Pyro for didactic purposes

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#1554]
The Architecture of Open Source Applications project hosts tiny educational versions of many pieces of software https://github.com/aosabook/500lines (recommended reading!). I think it would be helpful to have a similar examples/mini_pyro.py to demonstrate how e.g. how Pyro's effects library works.

## Tasks

- [x] #1553 `trace`, `replay`, `SVI`, `elbo`, and a simple example
- [x] #1578 rendered version on pyro.ai
- [x] #1583 comments throughout the file
- [x] #1589 `plate` with broadcasting
- [ ] #1599 `block` (@eb8680)

---- triaged ----
- ~~enumeration~~
- ~~`markov`~~

## Budget

All of pyro plus comments plus an example should fit into:
- 500 lines of code
- ~~1 single python file~~ 2 python files = 1 for example + 1 for library
