### ISSUE TITLE
Checklist for Pyro 0.3 release

### ISSUE THREAD

**Issue by neerajprad** [uber/pyro#1570]
- [x] Verify CUDA tests are running fine. @neerajprad 
 - [x] Update dockerfile if needed. @neerajprad, @jpchen 
 - [x] Collect release notes from all devs
 - [x] #1406 @jpchen
 - [x] #1655 Update `.travis.yml` and `setup.py` to use release version instead of the pinned nightly build. @neerajprad 
 - [x] #1655 Update README with setup instructions for dev.
 - [x] Verify that all [issues](https://github.com/uber/pyro/milestone/5) tagged with the pyro-0.3 release milestone are addressed.
 - [x] Cut release, and make announcements. @fritzo 
 - [x] Update documentation and tutorials on readthedocs. @jpchen

**Comment by fehiepsi** [comment]
Revising gp module too. ^^

**Comment by neerajprad** [comment]
> Revising gp module too. ^^

@fehiepsi - This is mostly just a checklist to tick off before cutting the release. All code related changes should have a milestone, and should be covered under `issues tagged with the pyro-0.3 milestone` check above.
