### ISSUE TITLE
FR: collapse messenger for composing infer_discrete

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#1722]
@eb8680 has been working on a `collapse` messenger that integrates out discrete random variables. `@collapse` is a simple wrapper around `infer_discrete` that additionally blocks discrete sample sites and adjusts log_prob tensors. This issue documents remaining work before the [collapse-messenger branch](https://github.com/uber/pyro/tree/collapse-messenger) can be merged.

## Tasks

- [ ] Add more tests of log_prob correctness
- [ ] Fix log_prob adjustment
- [ ] Fix issues with `poutine.block` interacting with `poutine.replay` (see also #1535 )
- [ ] Use `collapse` in `TraceEnum_ELBO`?

**Comment by fritzo** [comment]
@eb8680 would this resolve #1710 by allowing us to use a `collapse`d model inside `TraceMeanField_ELBO`? If so we should add this as a test.

**Comment by eb8680** [comment]
> would this resolve #1710 by allowing us to use a collapsed model inside TraceMeanField_ELBO? 

Hmm, not sure I see this - #1710 is specifically about the case of uncollapsed variables, right?
