### ISSUE TITLE
Implement TransformedDistribution.batch_log_pdf()

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#293]
Blocking #588 #592 

## Tasks
- [ ] Make `Bijector.log_det_jacobian()` return an elementwise result.
- [ ] Implement `TransformedDistribution.log_batch_pdf()` by vectorizing the computation in `TransformedDistribution.log_pd()`.
- [ ] Remove `TransformedDistribution.log_pd()` once `TransformedDistribution.log_batch_pdf()` is implemented.

**Comment by fritzo** [comment]
@martinjankowiak Would you mind doing this since you're most familiar with this?

**Comment by fritzo** [comment]
@martinjankowiak I'll code up a first pass of this.

**Comment by fritzo** [comment]
Already implemented upstream.
