### ISSUE TITLE
Migrate from .backward() to torch.autograd.grad()

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#628]
## Why?

A number of past algorithm development efforts have been made overly complex due to the side-effectful nature of `.backward()` (e.g. MAP #573 , HMC #611 , LAX in `TraceGraph_ELBO` https://github.com/uber/pyro/tree/lax, early attempts to support `enum_discrete` in `TraceGraph_ELBO`, Laplace approximation #590 ). These efforts would likely be easier if we switched from `.backward()` to `torch.autograd.grad(...)` in a few places in Pyro (maybe everywhere).

## How?

PyTorch has two autograd interfaces: `.backward()` is more side-effectful and `torch.autograd.grad(...)` is more functional. Pyro currently uses `.backward()` almost everywhere ([verlet integrator](https://github.com/uber/pyro/blob/dev/pyro/ops/integrator.py) is an exception). By replacing `.backward()` with more functional handling of gradients returned by `grad(...)` in Pyro's ELBO implementations, we could improve modularity.

Currently PyTorch optimizers do not support use of external gradients. @soumith [is open to the possibility](https://discuss.pytorch.org/t/using-optimizers-with-torch-autograd-grad/11078) of adding this support in 0.4. To ease migration Pyro could provide a temporary workaround in the `pyro.optim` layer to manually set `.grad` attributes of optimized tensors.

## Tasks

- [ ] Work with PyTorch devs to support `grad(...)` in torch optimizers https://github.com/pytorch/pytorch/issues/4179
- [ ] Replace `.backward()` with `grad(...)` in `Trace_ELBO`.
- [ ] Replace `.backward()` with `grad(...)` in `TraceGraph_ELBO`.

**Comment by martinjankowiak** [comment]
yeah let's do this. let me finish my v0 lax implementation first : )

**Comment by ngoodman** [comment]
does this have implications for performance? in particular, are there in-place gradients that we do using `.backward()` that we wouldn't be able to do in place with `.grad()`?

**Comment by martinjankowiak** [comment]
@ngoodman it may. in many cases it probably won't but we'll definitely have to do some tests and think things through carefully before we commit to anything. one place i could imagine a performance hit is elbo with `num_particles>1`.

**Comment by fritzo** [comment]
The motivating problems appear solved now that `Trace_ELBO` and `TraceEnum_ELBO` have `.differentiable_loss()` methods. Closing this issue for now; we can re-open if other motivating problems arise.
