### ISSUE TITLE
Master Task - Update broadcasting and batching semantics for Pyro Distributions

### ISSUE THREAD

**Issue by neerajprad** [uber/pyro#638]
We have made some major changes to the `torch.distributions` API, and would like to make this available in Pyro in its full generality. However, the current Pyro shape semantics are incompatible with this new API. 

Some of these incompatibilities are as follows:
 - The `batch` and `sample` dimensions in Pyro are conflated, which makes it confusing for the user to determine the shape of the distribution parameters to be supplied, i.e. it is common to provide identical distribution parameters only to impose a shape on the `sample`.
 - Any batching (i.e. `sample` dimensions) is restricted to a single dimension, and does not support arbitrary shaped sample sizes.
 - In the absence of scalar support, `batch_log_pdf` upcasts the resulting score by appending an additional `(1,)` rightmost dimension. In the case of PyTorch, we have tried to localize this behavior to only upcast when any dimension reduction results in a 0 sized tensor. This makes the migration to `torch.Scalar` simpler.

By the next PyTorch release, we would like to have this rich and updated API available to Pyro. @fritzo and I decided that it will simplify the transition if Pyro's `dev` branch only tries to maintain compatibility with `PyTorch's` master instead of the `release` version which it does now (refer to Phase 1.5).

The transition plan is as follows:

### Phase 1 - Changes in PyTorch:
- [x] Create implementations for all the Pyro distributions in PyTorch. These are being tracked at https://github.com/probtorch/pytorch/projects/1
- [x] #606 Build light wrappers around `pyro.distributions` in Pyro which preserve our current shape semantics.
- [x] #684 Delete Pyro distributions and distribution tests. Migrate all major testing to PyTorch.

### Phase 1.5 - Infra / internal changes to help with migration:
Can be done simultaneously with Phase 1. 
- [x] Create a lightweight torch wheel that can be periodically updated to reflect PyTorch master. This will be useful for CI testing of Pyro dev against PyTorch master. - Refer to [pytorch#4178](https://github.com/pytorch/pytorch/issues/4178), #670 
- [x] Make tutorials testable - tutorials need to be written using a format that allows for easy and fast testing of API related changes.
- [ ] Add versioning to tutorials - Given that some of our changes will not be backwards compatible, we should version our tutorials to make it easy for our users to refer to the relevant version depending on their version of Pyro install. (Ref. #639)
 
### Phase 2 - Internal change to Distributions API:
- [x] Move the `.__init__(batch_size=None)` argument to `.sample(sample_shape=torch.Size())`
- [x] Update the wrappers to expose the full generality of the `torch.distributions` API. Resolve incompatibilities in inference algorithms like `Trace_ELBO` and `TraceGraph_ELBO`.
- [x] Incorporate arbitrary batch dimensions in `iarange` #370 

  
  
- [x] Update all examples and tutorials to use the new API. - #726

**Comment by neerajprad** [comment]
@fritzo - Let me know if this looks okay, and feel free to make changes. We can add specific tasks too to track each of these sub-tasks.

**Comment by neerajprad** [comment]
Closing this. 

@jpchen - Regarding tutorial versioning, I suppose that we ended up deciding to just support the release branch for the tutorials, right?

**Comment by jpchen** [comment]
> support the release branch for the tutorials, right?

unless theres a compelling reason to support old versions in tutorials, i think thats a safe bet
