### ISSUE TITLE
Fix tutorials to accommodate new batching semantics

### ISSUE THREAD

**Issue by neerajprad** [uber/pyro#726]
The following tutorials need fixing with recent distribution broadcasting changes. You are highly encouraged to add your tutorials to the smoke test (refer to #694 for an example on how to do this). If you do so, @fritzo and I can help maintain these with any changes to the API, as we did with the AIR, gmm, and gp tutorials.

 - [x] `ss_vae_M2.py`. cc - @karalets, @rohitsingh0812 - #725 
 - [x] `dmm.py` - #721
 - [x] `dmm.py` #711 - Throws NAN loss after one epoch. Once this is resolved, I'll make a change so that tutorials throwing warnings (like this one) will fail the test on travis.
- [ ] `dmm.py` - #788 
 - [x] `bayesian_regression.py` - Possibly related - #717 @jpchen

**Comment by jpchen** [comment]
#717 is an issue with traceelbo and is not related to the new batching semantics. i tested regression with the current dev and it is fine, so marking that as complete and will address the other issue separately
