### ISSUE TITLE
Use PyTorch distributions directly in Pyro

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#732]
@eb8680 suggested entirely removing the `TorchDistribution` wrapper class from Pyro. Here's a proposal for how we might do that:

## Refactoring Plan

- [x] #736 Change `.batch_shape` and `.event_shape` from methods to properties. (This is currently violated by `RandomPrimitive`, which requires workarounds).
- [x] #752 Remove `RandomPrimitive` and prefer `Dist(**params)` over `dist, **params`. This makes sense since more of our distributions are becoming stateful (`TransformedDistribution`, `Rejector`). See [detailed comment](https://github.com/uber/pyro/issues/732#issuecomment-362454322) in discussion thread below.
- [x] #768 Remove `log_pdf_mask` since this can be achieved via `with poutine.scale(None, log_pdf_mask)`.
- [x] #769 Simplify `Distribution` to be a mixin class that provides compatibility with PyTorch distributions. This should provide `.reparameterized`, `.enumerable`, `.__call__()`, and `.score_parts()`.
- [x] #769 Move `extra_event_dims` and `sample_shape` args to a `Reshape` distribution.
- [x] #769 Remove `TorchDistribution` wrapper class
- [x] #794 Programmatically wrap PyTorch distributions, as Edward does with Tensorflow distributions.
- [ ] Rename all distribution parameters to match PyTorch names.

### Pros

- less code for Pyro to maintain
- allows Pyro to use any new PyTorch distributions that users create
- avoids duplicated of effort in implementing new distributions
- removing `RandomPrimitive` would speed up Pyro (especially important now that PyTorch distributions cache intermediate results and are more expensive to construct)

### Cons

- refactoring requires effort
- breaks existing users
- makes Pyro more susceptible to API changes upstream

See also #638

**Comment by neerajprad** [comment]
As I was working to incorporate transforms of distribution with constrained support in HMC, I wanted to start using

**Comment by neerajprad** [comment]
I think deprecation of `RandomPrimitive` might become important for the following reason - currently, the Pyro distribution API is inconsistent with respect to `torch.distributions` with regard to certain attributes like `batch_shape`, `event_shape` etc. which are properties in `torch.distributions` but methods in `pyro.distributions`. The reason why we have them as methods in Pyro is to be able to support `RandomPrimitive` instances which cannot support properties (as we are required to pipe in args/kwargs). 

I am currently blocked in using `torch.transforms` of distributions having constrained support in HMC due to this. This is because the `base_dist` that we pass to TransformedDistribution is not compatible between Pyro and PyTorch (due to the reasons above). I tried to modify the Distribution API to use the same interface as `torch.distributions` by removing args/kwargs and designating shape methods as properties, and got quite far with that (branch - https://github.com/uber/pyro/tree/distribution-api), but there are still a lot of instances where we use code like: 
```
batch_dims = len(shape) - msg['fn'].event_dim(*msg["args"], **msg["kwargs"])
``` 
within Pyro internals, and I do not see any easy non-hacky way to prevent that from happening unless we completely deprecate RandomPrimitive. Let me know your thoughts.

**Comment by fritzo** [comment]
It sounds like `RandomPrimitive` is blocking correct treatment of tensor shapes and batching. Since batching support is a priority for us in Pyro 0.2, it is probably worth the cost of dropping `RandomPrimitive` from Pyro. In summary:

### Pros of dropping `RandomPrimitive'

- Would allow correct handling of batch sizes in `TransformedDistribution`
- Would allow automatic handling of constraints in HMC
- Would save ~15% overhead in PyTorch distribution constructors (@jpchen noted this in November, @neerajprad measured the overhead in HMC)
- Would allow distributions to have properties and thus be closer to PyTorch distributions

### Cons of dropping `RandomPrimitive'

- Lots of code would break
- We would need to use `Normal(loc, scale)` rather than `normal, loc, scale` syntax

**Comment by fehiepsi** [comment]
> We would need to use Normal(loc, scale) rather than normal, loc, scale syntax

It sounds like a pros to me. ^^! With the first form, we can get sample, see the logprob, get mean/variance,... just by calling a method/property on it. When I learned Pyro through tutorials, I know `Normal` is a derived class from `pyro.dist.Distribution`, but I don't know the underlying mechanism of the second syntax in `pyro.sample(...)` statements. After seeing a comment of one of the developers that we can use the first syntax in `pyro.sample(...)`, I have been using the first syntax until now.

**Comment by jpchen** [comment]
>  I have been using the first syntax until now.

I have too in my personal development, but it is not written that way in our tutorials and from the q's ive been getting, it seems like almost all our users use distributions as a function. this will be a rather big breaking change

im onboard deprecating/removing it since the additional properties make the functional form less useful now.

**Comment by jpchen** [comment]
cc: @ngoodman

**Comment by eb8680** [comment]
I'm fine with getting rid of `RandomPrimitive`, although updating the syntax in most of our tests, examples, and tutorials will be a pain for us.  I don't think it will be a huge change for users relative to the other changes happening in the distributions.

**Comment by fritzo** [comment]
Closing. Renaming work can be moved to #827
