### ISSUE TITLE
Remove RandomPrimitive

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#752]
## Why?

- Motivated by moving closer to PyTorch distributions https://github.com/uber/pyro/issues/732#issuecomment-362454322
- Would allow a fix for #750 i.e. calling `site["fn"].size()`
- PyTorch distributions now cache things, and RandomPrimitive discards the cache
- RandomPrimitive is not compatible with properties
- PyTorch distributions are expensive to construct; `RandomPrimitive` constructs them repeatedly

## Tasks

- [x] #754 Make `sample_shape` a parameter of `Distribution.log_prob()` and `.enumerate_support()`
- [x] #759 Update profiling scripts
- [x] #757 Update tests (except distribution fixture)
- [x] #761 Update all examples
- [x] #762 Update distribution test fixture
- [x] #755 Update all tutorials
- [ ] #764 Remove  `RandomPrimitive`

**Comment by eb8680** [comment]
Do we still need our distribution tests after this?

**Comment by fritzo** [comment]
> Do we still need our distribution tests after this?

Some are redundant and can safely be removed. Others should remain, e.g. tests for `Rejector`, `Delta`, our `TorchDistribution` wrapper, our `SparseMultivariateNormal`, ...
