### ISSUE TITLE
Rename things before Pyro 0.2 release

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#827]
Here is a list of candidate renamings, feel free to edit or add:

### confirmed:

- [x] #932 `.enumerable` -> `.has_enumerate_support`
- [x] #932 `.analytic_mean()` -> `.mean`
- [x] #932 `.analytic_var()` -> `.variance`
- [x] #940 `batch_log_pdf` -> `log_prob`;   `log_pdf` -> `log_prob_sum`
- [x] #947 drop `pyro.observe` in favor of `pyro.sample`
- [x] #961 distribution parameter names (see also #732)
- [x] #959 `.reparameterized` -> `.has_rsample`
- [x] #1000 `Poutine` -> `Handler` (assigned to @eb8680 )
- [x] #1016 `.reshape(sample_shape)` -> `.expand_by(sample_shape)`
- [x] #1016 `.reshape(extra_event_dims=n)` -> `.independent(n)`
  (Tensorflow calls this [Independent(-, reinterpreted_batch_ndims=n)](https://www.tensorflow.org/api_docs/python/tf/contrib/distributions/Independent))

### triaged:
- ~~`config_enumerate` -> `mark_sites_for_enumeration`, or maybe `config_infer`~~

**Comment by eb8680** [comment]
Except for the `sample`/`rsample` distinction, we should rename all distribution methods and parameters to match `torch.distributions`.  We should also name all `log_pdf` things to `log_prob` in `Trace` and elsewhere, and `Poutine` to `Handler`.
