### ISSUE TITLE
Refactor and extend ELBO implementations

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#847]
This issue documents refactoring and enhancement of `Trace_ELBO` and `TraceGraph_ELBO` over a series of PRs. See also the related #816 and the motivating #846 and #828 .

## Why?

It has become clear while diagnosing #846 that `enum_discrete` requires stricter dependency structure than `Trace_ELBO` or `TraceGraph_ELBO` require, namely that variables in an `iarange` cannot have downstream dependents outside of that `iarange`. This motivates splitting out a new class `TraceEnum_ELBO` from the simpler `Trace_ELBO`, so that `Trace_ELBO` can be simpler, more flexible, more auditable as a reference implementation, and easier to for users to fork when defining their own `ELBO` implementations.

Furthermore, the `TensorTree` data structure we're using to implement `TraceEnum_ELBO` in #828 can later be used in `Trace_ELBO` to provide full support for batching (i.e. for Rao-Blackwellization based on coarse structure of `irange` and `iarange`, rather than fine dependency structure as used in `TraceGraph_ELBO`). This motivates an overhaul of `Trace_ELBO` before 0.2 release.

Note that `Trace_ELBO` has lost support for minibatch Rao-Blackwellization during our refactoring to support multiple batch dimensions. This functionality will be added back in before 0.2 release, and is already supported in #828.

## Steps

- [x] #848 Refactor to split `Trace_ELBO` into `TraceEnum_ELBO` + `Trace_ELBO`.
- [x] #828 Fix `TraceEnum_ELBO` to work correctly with `iarange`.
- [x] #863 Allow mixed reuse of `iarange` contexts (e.g. `context1 = pyro.iarange(...)`). This is needed to fix subsample scale bugs in `iarange`.
- [x] #872 Allow mixed reuse of `irange` iterators.
- [x] #865 Add nested `iarange` support to `Trace_ELBO` (using `MultiFrameTensor`), e.g. to Rao-Blackwellize over minibatches.
- [x] #867 Fix broadcasting in `TraceGraph_ELBO` (using `MultiFrameTensor`).
- [x] #894 Fix broadcasting in `TraceEnum_ELBO` (using `MultiFrameDice`).
- [x] #902 Clean up `iter_discrete_traces` after its implementation settles down.
- [x] #902 Add more tests
- [x] #903 Expose `Trace*_ELBO` in sphinx documentation.
- TRIAGED Use `score_parts.entropy_term` to "stick the landing" in `TraceEnum_ELBO`
