### ISSUE TITLE
Clarify GMM tutorial and add to pyro.ai/examples

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#879]
See https://github.com/uber/pyro/issues/635#issuecomment-368953014 for confusion due to nondescript variable names.
See #874 for reorganization of tutorial index. 

## Tasks

- [x] #900 rename `p` to `assignment_probs` or similar
- [x] #900 rename `ps` to `cluster_probs` or similar
- [x] #900 explain use of `pyro.param` in model rather than exclusively in guide
-  add tutorial to pyro.ai (will happen at next release)

**Comment by fritzo** [comment]
cc @vincent6606
