### ISSUE TITLE
Dependent Enumeration

### ISSUE THREAD

**Issue by karalets** [uber/pyro#915]
We have been discussing with @fritzo about getting a version of enumeration working that can do dependent variables, such as in an HMM. It seems that the current enumeration routines are pretty close to what is needed and this should be doable.

Also, @ngoodman had an example he has been using for how he solved that in webppl. 
It would be nice to take inspiration from that functionality for pyro.
Here are example-programs where this is tackled that I would love to write down in pyro:
http://dippl.org/chapters/04-factorseq.html

Leaving this here as a reminder for interested people to discuss.

## Related work

- Laurence Aitchison (2018) "Tensor monte carlo" [pdf](http://www.gatsby.ucl.ac.uk/~balaji/udl-camera-ready/UDL-26.pdf)

## Tasks

- [x] #1279 Avoid expanding in `.enumerate_support()`
- [x] #1289 Support `expand=False` in SVI
- [x] #1301 Support `expand=False` in HMC
- [x] #1302 Support local `num_particles` in `TracEnum_ELBO`
- [x] #1313 Support message passing in [Dice](https://github.com/uber/pyro/blob/ed58ec6/pyro/infer/util.py#L210)
- [x] #1315 Support `iarange` + message passing in `Dice`
- [x] #1318 Memoize the opt_einsum contract path
- [x] #1328 Marginalize out discrete variables in the model
- [x] Work around `torch.einsum`/`torch.bmm` performance issues https://github.com/pytorch/pytorch/issues/10661
- [x] #1340 Set `expand=False` by default
- [x] #1322 Support message passing in [EnumTraceProbEvaluator](https://github.com/uber/pyro/blob/6aca9eb/pyro/infer/mcmc/util.py#L8)
- [x] #1343 Support model enumeration at different `iarange`s in SVI
- [x] Expose model enumerated random variables for prediction in SVI
    - [x] #1359 via local marginals
    - [x] #1367 via forward-sample backward-filter

## Triaged Tasks

- Allow guide enumeration for prediction in SVI
- Support parallelization in `Empirical` (required by `Search`)
- Support enumeration in `Search` (#1226)
- ([advi-expand](https://github.com/uber/pyro/compare/trace-enum-expand...advi-expand?expand=1)) Support `expand=False` in `AutoDiscreteParallel`

**Comment by eb8680** [comment]
Can you be clearer about your goal?  The examples you cited are about incorporating intermediate constraints into enumeration so that partial traces that do not satisfy those intermediate constraints are not explored further.  See #772 for an implementation of a more advanced model from DIPPL that uses the same idea in sequential enumeration.

**Comment by fritzo** [comment]
I believe @karalets wants enumeration to work in models with Markov structure. Currently enumeration is exponentially expensive in the number of enumerated variables. For example in this HMM with Gaussian observations
```py
def model(data):
    init_probs = pyro.param("init_probs", torch.tensor([0.5, 0.5]),
                            constraint=constraints.simplex)
    transition_probs = pyro.param("init_probs", torch.tensor([[0.9, 0.1], [0.1, 0.9]]),
                                  constraint=constraints.simplex)
    locs = pyro.param("obs_locs", torch.tensor([-1, 1]))
    scales = pyro.param("obs_scales", torch.tensor([1, 1]),
                        constraint=constraints.positive)

    x = pyro.sample("x_init", dist.Categorical(init_probs))
    for i, y in enumerate(data):
        x = pyro.sample("x_{}".format(i), dist.Categorical(transition_probs[x]))
        pyro.sample("y_{}".format(i), dist.Normal(locs[x], scales[x]), obs=y)

@config_enumerate(default="parallel")
def guide(data):
    mean_field_probs = pyro.param("mean_field_probs", torch.ones(len(data), 2) / 2),
                                  constraint=constraints.simplex)
    for i in range(len(data)):
        pyro.sample("x_{}".format(i), dist.Categorical(mean_field_probs[i]))

inference = SVI(model, guide, Adam({'lr': 0.01}), 'ELBO', enumerate_discrete=True)
```
I believe Pyro will currently perform exact Baum-Welch but at exponential cost.

**Comment by fritzo** [comment]
Closing this task after lots of fun work. Let's move future improvements into more specific issues. @karalets thanks for suggesting this. 🎉
