### ISSUE TITLE
Update PyTorch version to use .arg_constraints

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#928]
Two upstream PRs merged this morning, one of which fixes the xfail added in #922:
- https://github.com/pytorch/pytorch/pull/5989 fixes `TransformedDistribution.params` and renames `.params` to `.arg_constraints`
- https://github.com/pytorch/pytorch/pull/5988 adds `MultivariateNormal.mean`, `.variance`, so we can remove our wrapper in pyro/distributions/torch.py

Let's update Pyro asap to the latest PyTorch version.

## Tasks

- [x] Update PyTorch version
- [x] Rename `.params` to `.arg_constraints` in all distributions
- [x] Remove xfail from https://github.com/uber/pyro/pull/922/files#r176948722
- [ ] ~Remove context manager workround from https://github.com/uber/pyro/pull/922/files#r176948808~
- [x] Remove the `MultivariateNormal` wrapper in pyro/distributions/torch.py

**Comment by neerajprad** [comment]
> Remove context manager workround from https://github.com/uber/pyro/pull/922/files#r176948808

The context manager is needed so as not to spend a lot of time doing argument validation (only for expensive NUTS/HMC tests). SVI does not need this.
